Fix loader-boot in application notify_alive which may break other stuff in linux
The service stopping when is already stopped takes some resources and in some special cases when videos are playing, or are switching omxplayer, the following error can happen:
Call to flock failed: Resource temporarily unavailable
ERROR: loader-boot stopped by something else

So adding --ifstarted argument would do the stop of service only when is running, so it could happend on production only once after boot